/**
 * Concatenates source CSS into production bundles.
 * Source files under styles/ are never modified — only read and merged.
 *
 * Run: node scripts/build-css.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const stylesDir = path.join(root, "styles");
const outDir = path.join(stylesDir, "bundles");

/** Load order must match cascade expectations (section then responsive). */
const bundles = {
  "critical.bundle.css": [
    "tokens.css",
    "base.css",
    "motion.css",
    "components/navbar.css",
    "responsive/navbar.css",
    "components/activity-card.css",
    "components/balance-card.css",
    "sections/hero.css",
    "responsive/hero.css",
  ],
  "main.bundle.css": [
    "sections/solutions.css",
    "responsive/solutions.css",
    "sections/core-banking.css",
    "responsive/core-banking.css",
    "sections/efficient-core.css",
    "responsive/efficient-core.css",
    "sections/paperless.css",
    "responsive/paperless.css",
    "sections/marquee.css",
    "sections/digital.css",
    "responsive/digital.css",
    "sections/insights.css",
    "responsive/insights.css",
    "sections/case-studies.css",
    "responsive/case-studies.css",
    "sections/paperless-cta.css",
    "responsive/paperless-cta.css",
    "sections/site-footer.css",
    "responsive/site-footer.css",
  ],
};

function readCss(relativePath) {
  const filePath = path.join(stylesDir, relativePath);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing CSS source: ${relativePath}`);
  }
  return fs.readFileSync(filePath, "utf8").trimEnd();
}

function buildBundle(name, files) {
  const parts = files.map((file) => {
    const content = readCss(file);
    return `/* ===== ${file} ===== */\n${content}`;
  });

  const banner = `/* ${name} — generated by scripts/build-css.mjs — do not edit */\n`;
  return `${banner}\n${parts.join("\n\n")}\n`;
}

fs.mkdirSync(outDir, { recursive: true });

for (const [filename, files] of Object.entries(bundles)) {
  const output = buildBundle(filename, files);
  const outPath = path.join(outDir, filename);
  fs.writeFileSync(outPath, output, "utf8");
  const kb = (Buffer.byteLength(output, "utf8") / 1024).toFixed(1);
  console.log(`Wrote ${path.relative(root, outPath)} (${kb} KB, ${files.length} files)`);
}

console.log("CSS bundles built successfully.");
